name: gaius-process
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  gaius-process:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Run gaius build
      run: |
        dotnet ./bin/gaius/gaius.dll build --yes
    - name: Push generated files to gh-pages branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: _generated
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}